name: CI

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: HeySiri
    jobs:
      - job:
        displayName: Unit tests
        steps:
          - task: DotNetCoreCLI@2
            displayName: HeySiri.Core.Tests
            inputs:
              workingDirectory: $(Agent.BuildDirectory)/s/tests/HeySiri.Core.Tests
              command: test
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              containerRegistry: DockerHub
              Dockerfile: $(Agent.BuildDirectory)/s/src/Dockerfile
              buildContext: $(Agent.BuildDirectory)/s/src
              repository: doghappy/heysiri
              tags: |
                latest
